version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
   os: ubuntu-20.04
   tools:
     python: "3.12"

python:

   install:
      - method: pip
        path: .
        extra_requirements:
          - doc
